import { FormEvent, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, ArrowLeft, Check, ShieldCheck } from "lucide-react";
import { useFirewall } from "@/lib/store";

export default function Signup() {
  const navigate = useNavigate();
  const { login } = useFirewall();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [error, setError] = useState("");
  const strength = useMemo(() => { let score = 0; if (password.length >= 8) score++; if (/[A-Z]/.test(password)) score++; if (/[0-9]/.test(password)) score++; return score; }, [password]);
  function submit(event: FormEvent) { event.preventDefault(); if (password !== confirm) { setError("Passwords do not match"); return; } if (strength < 3) { setError("Please meet all password requirements"); return; } login(email || "merchant@acme.co"); navigate("/dashboard"); }
  return <AuthShell title="Create your workspace" subtitle="Set up a protected payment workspace in under a minute."><form onSubmit={submit} className="space-y-4"><Field label="Business / merchant name" value={name} onChange={setName} placeholder="Acme Commerce" /><Field label="Work email" type="email" value={email} onChange={setEmail} placeholder="merchant@company.com" /><div><label className="mb-2 block text-xs font-medium text-white/70">Password</label><input required type="password" value={password} onChange={(e) => { setPassword(e.target.value); setError(""); }} className="h-11 w-full rounded-xl border border-white/10 bg-black/10 px-4 text-sm text-white outline-none focus:border-brand-blue focus:ring-2 focus:ring-brand-blue/20" /><div className="mt-2 flex gap-1.5">{[1,2,3].map((n) => <span key={n} className={`h-1.5 flex-1 rounded-full ${strength >= n ? strength === 1 ? "bg-destructive" : strength === 2 ? "bg-warning" : "bg-success" : "bg-white/10"}`} />)}</div><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-[10px] text-white/45"><span className={password.length >= 8 ? "text-success" : ""}><Check className="mr-1 inline h-3 w-3" />8+ characters</span><span className={/[A-Z]/.test(password) ? "text-success" : ""}><Check className="mr-1 inline h-3 w-3" />1 uppercase</span><span className={/[0-9]/.test(password) ? "text-success" : ""}><Check className="mr-1 inline h-3 w-3" />1 number</span></div></div><Field label="Confirm password" type="password" value={confirm} onChange={(v) => { setConfirm(v); setError(""); }} placeholder="Re-enter your password" />{error && <p className="text-xs text-red-300">{error}</p>}<button className="group mt-2 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-brand-blue text-sm font-semibold text-white transition hover:brightness-110">Create account <ArrowRight className="h-4 w-4 transition group-hover:translate-x-0.5" /></button></form><p className="mt-6 text-center text-xs text-white/45">Already have an account? <Link to="/login" className="font-semibold text-brand-blue hover:underline">Log in</Link></p></AuthShell>;
}
function Field({ label, value, onChange, placeholder, type = "text" }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; type?: string }) { return <label className="block"><span className="mb-2 block text-xs font-medium text-white/70">{label}</span><input required type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="h-11 w-full rounded-xl border border-white/10 bg-black/10 px-4 text-sm text-white outline-none placeholder:text-white/25 focus:border-brand-blue focus:ring-2 focus:ring-brand-blue/20" /></label> }
function AuthShell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="relative flex min-h-screen items-center justify-center overflow-hidden bg-brand-cadet px-6 py-10 text-white"><div className="pointer-events-none absolute inset-0 bg-grid-glow opacity-80" /><div className="relative w-full max-w-md"><Link to="/" className="mb-7 inline-flex items-center gap-2 text-sm text-white/50 hover:text-white"><ArrowLeft className="h-4 w-4" />Back to home</Link><div className="rounded-3xl border border-white/10 bg-white/[0.05] p-7 shadow-2xl backdrop-blur-md sm:p-9"><div className="mb-7 flex h-11 w-11 items-center justify-center rounded-2xl bg-brand-blue/15 ring-1 ring-brand-blue/30"><ShieldCheck className="h-5 w-5 text-brand-blue" /></div><h1 className="text-2xl font-bold tracking-tight">{title}</h1><p className="mt-2 text-sm text-white/50">{subtitle}</p><div className="mt-7">{children}</div></div></div></div> }
