import { FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, ArrowRight, CheckCircle2, ShieldCheck } from "lucide-react";

export function ForgotPassword() {
  const [sent, setSent] = useState(false);
  function submit(e: FormEvent) { e.preventDefault(); setSent(true); }
  return <Auth title="Reset your password" subtitle={sent ? "If an account exists for that email, a reset link has been sent." : "Enter your email and we’ll send a secure reset link."}><form onSubmit={submit} className="space-y-4"><label className="block"><span className="mb-2 block text-xs font-medium text-white/70">Work email</span><input required type="email" placeholder="merchant@company.com" className="h-11 w-full rounded-xl border border-white/10 bg-black/10 px-4 text-sm text-white outline-none focus:border-brand-blue" /></label>{sent && <p className="rounded-xl bg-success/10 p-3 text-xs text-green-200"><CheckCircle2 className="mr-1 inline h-4 w-4" />Check your inbox to continue.</p>}<button className="flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-brand-blue text-sm font-semibold">Send reset link <ArrowRight className="h-4 w-4" /></button></form><p className="mt-6 text-center text-xs text-white/45"><Link to="/login" className="text-brand-blue hover:underline">Back to login</Link></p></Auth>;
}
export function ResetPassword() {
  const navigate = useNavigate(); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState("");
  function submit(e: FormEvent) { e.preventDefault(); if (password.length < 8 || !/[A-Z]/.test(password) || !/[0-9]/.test(password)) return setError("Use 8+ characters with an uppercase letter and number"); if (password !== confirm) return setError("Passwords do not match"); navigate("/login"); }
  return <Auth title="Set a new password" subtitle="Choose a strong password for your merchant workspace."><form onSubmit={submit} className="space-y-4"><Password label="New password" value={password} onChange={setPassword} /><Password label="Confirm password" value={confirm} onChange={setConfirm} />{error && <p className="text-xs text-red-300">{error}</p>}<button className="flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-brand-blue text-sm font-semibold">Update password <ArrowRight className="h-4 w-4" /></button></form></Auth>;
}
function Password({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <label className="block"><span className="mb-2 block text-xs font-medium text-white/70">{label}</span><input required type="password" value={value} onChange={(e) => onChange(e.target.value)} className="h-11 w-full rounded-xl border border-white/10 bg-black/10 px-4 text-sm text-white outline-none focus:border-brand-blue" /></label> }
function Auth({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="relative flex min-h-screen items-center justify-center overflow-hidden bg-brand-cadet px-6 py-10 text-white"><div className="pointer-events-none absolute inset-0 bg-grid-glow" /><div className="relative w-full max-w-md"><Link to="/" className="mb-7 inline-flex items-center gap-2 text-sm text-white/50 hover:text-white"><ArrowLeft className="h-4 w-4" />Back to home</Link><div className="rounded-3xl border border-white/10 bg-white/[0.05] p-7 shadow-2xl backdrop-blur-md sm:p-9"><div className="mb-7 flex h-11 w-11 items-center justify-center rounded-2xl bg-brand-blue/15"><ShieldCheck className="h-5 w-5 text-brand-blue" /></div><h1 className="text-2xl font-bold">{title}</h1><p className="mt-2 text-sm text-white/50">{subtitle}</p><div className="mt-7">{children}</div></div></div></div> }
